project:
  type: website
  output-dir: docs

website:
  title: "Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Drama.qmd
        text: Drama
      - href: reflection.qmd
        text: Reflection

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



